"""add gate pass asset association

Revision ID: 9367e22550ed
Revises: e7c2582811a1
Create Date: 2026-09-16 14:18:45.109823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9367e22550ed'
down_revision: Union[str, Sequence[str], None] = 'e7c2582811a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_pass_assets',
    sa.Column('gate_pass_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_pass_id'], ['gate_passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_pass_id', 'asset_id', name='uq_gate_pass_asset')
    )
    op.create_index(op.f('ix_gate_pass_assets_asset_id'), 'gate_pass_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_gate_pass_assets_gate_pass_id'), 'gate_pass_assets', ['gate_pass_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_pass_assets_gate_pass_id'), table_name='gate_pass_assets')
    op.drop_index(op.f('ix_gate_pass_assets_asset_id'), table_name='gate_pass_assets')
    op.drop_table('gate_pass_assets')
    # ### end Alembic commands ###
