"""create assets and asset tag tables

Revision ID: b1a7aa3a9042
Revises: 8999295e99b3
Create Date: 2026-09-16 10:27:11.732032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a7aa3a9042'
down_revision: Union[str, Sequence[str], None] = '8999295e99b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), server_default='active', nullable=False),
    sa.Column('current_zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_current_zone_id'), 'assets', ['current_zone_id'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tag_uid', sa.String(length=255), nullable=False),
    sa.Column('tag_type', sa.Enum('QR', 'RFID', 'NFC', name='asset_tag_type'), server_default='QR', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_tags_asset_id'), 'asset_tags', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_tags_tag_uid'), 'asset_tags', ['tag_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_tags_tag_uid'), table_name='asset_tags')
    op.drop_index(op.f('ix_asset_tags_asset_id'), table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_current_zone_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
