"""add gate passes

Revision ID: bf17e4f60192
Revises: 85417719de93
Create Date: 2026-09-16 12:40:30.852794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf17e4f60192'
down_revision: Union[str, Sequence[str], None] = '85417719de93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_passes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('pass_number', sa.String(length=100), nullable=False),
    sa.Column('pass_type', sa.Enum('ENTRY', 'EXIT', 'DELIVERY', 'TRANSFER', name='gate_pass_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'USED', 'EXPIRED', 'CANCELLED', name='gate_pass_status'), server_default='PENDING', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_passes_approved_by'), 'gate_passes', ['approved_by'], unique=False)
    op.create_index(op.f('ix_gate_passes_created_by'), 'gate_passes', ['created_by'], unique=False)
    op.create_index(op.f('ix_gate_passes_gate_id'), 'gate_passes', ['gate_id'], unique=False)
    op.create_index(op.f('ix_gate_passes_location_id'), 'gate_passes', ['location_id'], unique=False)
    op.create_index(op.f('ix_gate_passes_organization_id'), 'gate_passes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gate_passes_pass_number'), 'gate_passes', ['pass_number'], unique=True)
    op.create_index(op.f('ix_gate_passes_vehicle_id'), 'gate_passes', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_passes_vehicle_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_pass_number'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_organization_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_location_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_gate_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_created_by'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_approved_by'), table_name='gate_passes')
    op.drop_table('gate_passes')
    # ### end Alembic commands ###
