"""add movement events

Revision ID: c493381ee3c3
Revises: b1a7aa3a9042
Create Date: 2026-09-16 10:47:49.636759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c493381ee3c3'
down_revision: Union[str, Sequence[str], None] = 'b1a7aa3a9042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_events',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('from_zone_id', sa.UUID(), nullable=True),
    sa.Column('to_zone_id', sa.UUID(), nullable=True),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('ENTRY', 'EXIT', 'TRANSFER', 'CHECK_IN', 'CHECK_OUT', name='movement_event_type'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_events_asset_id'), 'movement_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_movement_events_device_id'), 'movement_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_movement_events_from_zone_id'), 'movement_events', ['from_zone_id'], unique=False)
    op.create_index(op.f('ix_movement_events_gate_id'), 'movement_events', ['gate_id'], unique=False)
    op.create_index(op.f('ix_movement_events_idempotency_key'), 'movement_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_movement_events_location_id'), 'movement_events', ['location_id'], unique=False)
    op.create_index(op.f('ix_movement_events_to_zone_id'), 'movement_events', ['to_zone_id'], unique=False)
    op.create_index(op.f('ix_movement_events_triggered_by'), 'movement_events', ['triggered_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_events_triggered_by'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_to_zone_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_location_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_idempotency_key'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_gate_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_from_zone_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_device_id'), table_name='movement_events')
    op.drop_index(op.f('ix_movement_events_asset_id'), table_name='movement_events')
    op.drop_table('movement_events')
    # ### end Alembic commands ###
