"""add devices and link movement events

Revision ID: e7c2582811a1
Revises: bf17e4f60192
Create Date: 2026-09-16 14:05:51.248443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c2582811a1'
down_revision: Union[str, Sequence[str], None] = 'bf17e4f60192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_uid', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('QR_SCANNER', 'RFID_READER', 'GATE_CONTROLLER', 'ANPR_CAMERA', 'IOT_SENSOR', name='device_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_device_uid'), 'devices', ['device_uid'], unique=True)
    op.create_index(op.f('ix_devices_location_id'), 'devices', ['location_id'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.alter_column(
        'movement_events',
        'device_id',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using='device_id::uuid',
    )

    op.create_foreign_key(
        'fk_movement_events_device_id',
        'movement_events',
        'devices',
        ['device_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        'fk_movement_events_device_id',
        'movement_events',
        type_='foreignkey',
    )

    op.alter_column(
        'movement_events',
        'device_id',
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        postgresql_using='device_id::varchar',
    )
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_location_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_uid'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
