"""add alerts

Revision ID: eb073c0e2a67
Revises: c493381ee3c3
Create Date: 2026-09-16 12:22:01.257342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb073c0e2a67'
down_revision: Union[str, Sequence[str], None] = 'c493381ee3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('movement_event_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('UNAUTHORIZED_MOVEMENT', 'ABNORMAL_MOVEMENT', 'GATE_VIOLATION', 'MOVEMENT_OUTSIDE_ALLOWED_HOURS', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alert_status'), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movement_event_id'], ['movement_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_acknowledged_by'), 'alerts', ['acknowledged_by'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_location_id'), 'alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_alerts_movement_event_id'), 'alerts', ['movement_event_id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved_by'), 'alerts', ['resolved_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_resolved_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_movement_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_location_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged_by'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
